/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);

extern void test_FiveUpdatesCalibrateUnit(void);
extern void test_ConstantInputProducesNoFlush(void);
extern void test_ReducingInputProducesFlush(void);
extern void test_IncreasingInputProducesFlushEnd(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UNITY_BEGIN();
  RUN_TEST(test_FiveUpdatesCalibrateUnit, 0);
  RUN_TEST(test_ConstantInputProducesNoFlush, 1);
  RUN_TEST(test_ReducingInputProducesFlush, 2);
  RUN_TEST(test_IncreasingInputProducesFlushEnd, 3);

  return (UnityEnd());
}
